using CryptoExchange.Net.Authentication;

namespace Bitget.Net
{
    /// <summary>
    /// Bitget credentials
    /// </summary>
    public class BitgetCredentials : ApiCredentials
    {
        internal CredentialPair Credential { get; set; }
        internal string? Passphrase =>
            HMAC?.Pass 
            ?? RSAXml?.Pass
#if NETSTANDARD2_1_OR_GREATER || NET7_0_OR_GREATER
            ?? RSAPem?.Pass
#endif
            ;

        public HMACCredential? HMAC
        {
            get => Credential as HMACCredential;
            set { if (value != null) Credential = value; }
        }

        public RSAXmlCredential? RSAXml
        {
            get => Credential as RSAXmlCredential;
            set { if (value != null) Credential = value; }
        }

#if NETSTANDARD2_1_OR_GREATER || NET7_0_OR_GREATER
        public RSAPemCredential? RSAPem
        {
            get => Credential as RSAPemCredential;
            set { if (value != null) Credential = value; }
        }
#endif

        public BitgetCredentials WithHMAC(string key, string secret, string passphrase)
        {
            if (Credential != null) throw new InvalidOperationException("Credentials already set");

            Credential = new HMACCredential(key, secret, passphrase);
            return this;
        }

        public BitgetCredentials WithRSAXml(string key, string privateKey)
        {
            if (Credential != null) throw new InvalidOperationException("Credentials already set");

            Credential = new RSAXmlCredential(key, privateKey);
            return this;
        }

#if NETSTANDARD2_1_OR_GREATER || NET7_0_OR_GREATER
        public BitgetCredentials WithRSAPem(string key, string privateKey)
        {
            if (Credential != null) throw new InvalidOperationException("Credentials already set");

            Credential = new RSAPemCredential(key, privateKey);
            return this;
        }
#endif

        /// <inheritdoc />
        public override ApiCredentials Copy() => new BitgetCredentials { Credential = Credential };


//        /// <summary>
//        /// Create API credentials using an API key and secret generated by the server. This assumes HMAC authentication. If you want to use RSA authentication, use the appropriate constructor or static method instead.
//        /// </summary>
//        /// <param name="apiKey">The API key</param>
//        /// <param name="secret">The API secret</param>
//        /// <param name="passphrase">The API passphrase</param>
//        public BitgetCredentials(string apiKey, string secret, string passphrase) : this(new HMACCredential(apiKey, secret, passphrase)) { }

//        /// <summary>
//        /// Create Bitget credentials using HMAC credentials
//        /// </summary>
//        /// <param name="credential">The HMAC credentials</param>
//        public BitgetCredentials(HMACCredential credential) : base(credential) { }

//#if NETSTANDARD2_1_OR_GREATER || NET7_0_OR_GREATER
//        /// <summary>
//        /// Create Bitget credentials using RSA credentials in PEM format
//        /// </summary>
//        /// <param name="rsaCredential">RSA credentials</param>
//        public BitgetCredentials(RSAPemCredential rsaCredential)
//            : base(rsaCredential)
//        {
//        }
//#endif
//        /// <summary>
//        /// Create Bitget credentials using RSA credentials in XML format
//        /// </summary>
//        /// <param name="rsaCredential">RSA credentials</param>
//        public BitgetCredentials(RSAXmlCredential rsaCredential)
//            : base(rsaCredential)
//        {
//        }

//        /// <inheritdoc />
//#pragma warning disable CS0618 // Type or member is obsolete
//        public override ApiCredentials Copy() => new BitgetCredentials { CredentialPairs = CredentialPairs };
//#pragma warning restore CS0618 // Type or member is obsolete
    }
}
