using CryptoExchange.Net.Authentication;

namespace Bitget.Net
{
    /// <summary>
    /// Bitget credentials
    /// </summary>
    public class BitgetCredentials : ApiCredentials
    {
        /// <summary>
        /// Provided credential type
        /// </summary>
        public ApiCredentialsType CredentialType => CredentialPairs.First().CredentialType;

        internal string? Passphrase =>
            CredentialType == ApiCredentialsType.Hmac ? GetCredential<HMACCredential>()?.Pass
            : CredentialType == ApiCredentialsType.Rsa ? GetCredential<RSACredential>()?.Pass
            : null;

        /// <summary>
        /// </summary>
        [Obsolete("Parameterless constructor is only for deserialization purposes and should not be used directly. Use parameterized constructor instead.")]
        public BitgetCredentials() { }

        /// <summary>
        /// Create API credentials using an API key and secret generated by the server. This assumes HMAC authentication. If you want to use RSA authentication, use the appropriate constructor or static method instead.
        /// </summary>
        /// <param name="apiKey">The API key</param>
        /// <param name="secret">The API secret</param>
        /// <param name="passphrase">The API passphrase</param>
        public BitgetCredentials(string apiKey, string secret, string passphrase) : this(new HMACCredential(apiKey, secret, passphrase)) { }

        /// <summary>
        /// Create Bitget credentials using HMAC credentials
        /// </summary>
        /// <param name="credential">The HMAC credentials</param>
        public BitgetCredentials(HMACCredential credential) : base(credential) { }

#if NETSTANDARD2_1_OR_GREATER || NET7_0_OR_GREATER
        /// <summary>
        /// Create Bitget credentials using RSA credentials in PEM format
        /// </summary>
        /// <param name="rsaCredential">RSA credentials</param>
        public BitgetCredentials(RSAPemCredential rsaCredential)
            : base(rsaCredential)
        {
        }
#endif
        /// <summary>
        /// Create Bitget credentials using RSA credentials in XML format
        /// </summary>
        /// <param name="rsaCredential">RSA credentials</param>
        public BitgetCredentials(RSAXmlCredential rsaCredential)
            : base(rsaCredential)
        {
        }

        /// <inheritdoc />
#pragma warning disable CS0618 // Type or member is obsolete
        public override ApiCredentials Copy() => new BitgetCredentials { CredentialPairs = CredentialPairs };
#pragma warning restore CS0618 // Type or member is obsolete
    }
}
